from sqlalchemy.schema import CreateTable
from sqlalchemy import create_engine
from app.core.database import Base
from app.models import *  # Import all models to register them
from app.models.quiz import QuizQuestion, QuizAttempt # Explicit import just in case

def dump_schema():
    """Generates SQL CREATE statements for all models"""
    # Use a mock engine
    engine = create_engine('postgresql://mock')
    
    with open('schema.sql', 'w') as f:
        f.write("-- ALIF24 PLATFORM SCHEMA --\n")
        f.write("-- Generated by helper script --\n\n")
        
        # Sort tables directly if possible or just rely on metadata
        # SQLAlchemy usually handles foreign keys order in create_all, but not in individual CreateTable
        # We will iterate through sorted tables
        
        sorted_tables = Base.metadata.sorted_tables
        
        for table in sorted_tables:
            create_sql = CreateTable(table).compile(engine)
            f.write(f"{create_sql};\n\n")

if __name__ == "__main__":
    try:
        dump_schema()
        print("Schema generated in schema.sql")
    except Exception as e:
        print(f"Error: {e}")
