-- ALIF24 PLATFORM SCHEMA --
-- Generated by helper script --

CREATE TYPE achievementtype AS ENUM ('BADGE', 'TROPHY', 'CERTIFICATE', 'MILESTONE');

CREATE TYPE achievementcategory AS ENUM ('LEARNING', 'STREAK', 'SOCIAL', 'GAME', 'SPECIAL');

CREATE TYPE prizecategory AS ENUM ('toy', 'book', 'stationery', 'game', 'digital', 'other');

CREATE TYPE userrole AS ENUM ('moderator', 'organization', 'teacher', 'parent', 'student');

CREATE TYPE accountstatus AS ENUM ('pending', 'active', 'suspended', 'deleted');

CREATE TYPE gametype AS ENUM ('PUZZLE', 'MEMORY', 'MATCHING', 'QUIZ', 'ADVENTURE', 'COUNTING', 'SPELLING');

CREATE TYPE moderatorroletype AS ENUM ('ceo', 'cto', 'methodist');

CREATE TYPE olympiadsubject AS ENUM ('math', 'uzbek', 'russian', 'english', 'logic', 'general');

CREATE TYPE olympiadstatus AS ENUM ('draft', 'upcoming', 'active', 'finished', 'cancelled');

CREATE TYPE paymentprovider AS ENUM ('click', 'payme', 'uzum', 'manual');

CREATE TYPE paymentstatus AS ENUM ('pending', 'completed', 'failed', 'refunded');

CREATE TYPE leadstatus AS ENUM ('NEW', 'CONTACTED', 'TRIAL_LESSON', 'NEGOTIATION', 'WON', 'LOST');

CREATE TYPE childrelationship AS ENUM ('mother', 'father', 'grandmother', 'grandfather', 'guardian', 'other');

CREATE TYPE teacherstatus AS ENUM ('pending', 'approved', 'rejected');

CREATE TYPE activitytype AS ENUM ('CALL', 'MEETING', 'NOTE', 'TASK');

CREATE TYPE lessontype AS ENUM ('VIDEO', 'INTERACTIVE', 'READING', 'QUIZ', 'ACTIVITY');

CREATE TYPE livequizstatus AS ENUM ('created', 'waiting', 'active', 'paused', 'finished');

CREATE TYPE participationstatus AS ENUM ('registered', 'started', 'completed', 'disqualified');

CREATE TYPE subscriptiontier AS ENUM ('trial', 'standard', 'premium');

CREATE TYPE transactiontype AS ENUM ('lesson_complete', 'game_win', 'quiz_correct', 'olympiad_first', 'olympiad_second', 'olympiad_third', 'olympiad_participation', 'daily_bonus', 'withdrawal', 'prize_redemption', 'admin_adjustment');

CREATE TYPE withdrawalstatus AS ENUM ('pending', 'processing', 'completed', 'rejected');

CREATE TYPE participantstate AS ENUM ('joined', 'ready', 'answering', 'waiting', 'finished', 'disconnected');

CREATE TYPE progressstatus AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');

CREATE TYPE teacherlessontype AS ENUM ('HARF', 'RHARF', 'MATH', 'CUSTOM');

CREATE TYPE testtype AS ENUM ('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', 'MATCHING', 'MIXED');


CREATE TABLE achievements (
	id UUID NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	name_uz VARCHAR(100) NOT NULL, 
	name_ru VARCHAR(100) NOT NULL, 
	description TEXT, 
	description_uz TEXT, 
	description_ru TEXT, 
	icon VARCHAR(500), 
	type achievementtype, 
	category achievementcategory, 
	criteria JSON, 
	points_reward INTEGER, 
	is_active BOOLEAN, 
	"order" INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE avatars (
	id UUID NOT NULL, 
	key VARCHAR(50) NOT NULL, 
	display_name VARCHAR(100) NOT NULL, 
	display_name_uz VARCHAR(100) NOT NULL, 
	display_name_ru VARCHAR(100) NOT NULL, 
	image_url VARCHAR(500) NOT NULL, 
	is_active BOOLEAN, 
	sort_order INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (key)
)

;


CREATE TABLE guest_sessions (
	id UUID NOT NULL, 
	session_token VARCHAR(255) NOT NULL, 
	fingerprint VARCHAR(255), 
	ip_address VARCHAR(50), 
	content_accessed_count INTEGER, 
	first_content_type VARCHAR(50), 
	first_content_id VARCHAR(100), 
	is_active BOOLEAN, 
	requires_login BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	converted_to_user_id UUID, 
	converted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE phone_verifications (
	id UUID NOT NULL, 
	phone VARCHAR(20) NOT NULL, 
	code VARCHAR(6) NOT NULL, 
	telegram_chat_id VARCHAR(50), 
	verified BOOLEAN, 
	attempts INTEGER, 
	max_attempts INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE prizes (
	id UUID NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT, 
	category prizecategory, 
	image_url VARCHAR(500), 
	coin_price INTEGER NOT NULL, 
	stock_quantity INTEGER, 
	is_active BOOLEAN, 
	is_digital BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id)
)

;


CREATE TABLE quiz_questions (
	id UUID NOT NULL, 
	question_text VARCHAR NOT NULL, 
	options JSON NOT NULL, 
	correct_option_index INTEGER NOT NULL, 
	coins_reward INTEGER, 
	category VARCHAR, 
	difficulty VARCHAR, 
	is_active BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE subjects (
	id UUID NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	name_uz VARCHAR(100) NOT NULL, 
	name_ru VARCHAR(100) NOT NULL, 
	description TEXT, 
	description_uz TEXT, 
	description_ru TEXT, 
	icon VARCHAR(500), 
	color VARCHAR(20), 
	"order" INTEGER, 
	is_active BOOLEAN, 
	age_range JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE telegram_users (
	id UUID NOT NULL, 
	user_id UUID, 
	telegram_chat_id VARCHAR(50) NOT NULL, 
	telegram_username VARCHAR(100), 
	telegram_first_name VARCHAR(100), 
	telegram_last_name VARCHAR(100), 
	phone VARCHAR(20), 
	notifications_enabled BOOLEAN, 
	daily_report_enabled BOOLEAN, 
	achievement_alerts_enabled BOOLEAN, 
	language VARCHAR(5), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	last_interaction_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
)

;


CREATE TABLE users (
	id UUID NOT NULL, 
	email VARCHAR(255), 
	phone VARCHAR(20), 
	password_hash VARCHAR(255), 
	username VARCHAR(50), 
	pin_code VARCHAR(6), 
	parent_id UUID, 
	first_name VARCHAR(100) NOT NULL, 
	last_name VARCHAR(100) NOT NULL, 
	avatar VARCHAR(500), 
	date_of_birth DATE, 
	role userrole NOT NULL, 
	status accountstatus, 
	language VARCHAR(5), 
	timezone VARCHAR(50), 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES users (id)
)

;


CREATE TABLE games (
	id UUID NOT NULL, 
	subject_id UUID, 
	name VARCHAR(200) NOT NULL, 
	name_uz VARCHAR(200) NOT NULL, 
	name_ru VARCHAR(200) NOT NULL, 
	description TEXT, 
	description_uz TEXT, 
	description_ru TEXT, 
	type gametype, 
	level INTEGER, 
	age_min INTEGER, 
	age_max INTEGER, 
	config JSON, 
	thumbnail VARCHAR(500), 
	points_reward INTEGER, 
	time_limit INTEGER, 
	is_active BOOLEAN, 
	total_plays INTEGER, 
	average_score FLOAT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(subject_id) REFERENCES subjects (id)
)

;


CREATE TABLE moderator_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	role_type moderatorroletype NOT NULL, 
	permissions JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
)

;


CREATE TABLE notification_logs (
	id UUID NOT NULL, 
	user_id UUID, 
	notification_type VARCHAR(20) NOT NULL, 
	recipient VARCHAR(255) NOT NULL, 
	message TEXT NOT NULL, 
	status VARCHAR(20), 
	error_message TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	sent_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

;


CREATE TABLE notifications (
	id UUID NOT NULL, 
	user_id UUID, 
	title VARCHAR(255), 
	message TEXT NOT NULL, 
	is_read BOOLEAN, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

;


CREATE TABLE olympiads (
	id UUID NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	description TEXT, 
	subject olympiadsubject, 
	min_age INTEGER, 
	max_age INTEGER, 
	registration_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	registration_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	start_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_time TIMESTAMP WITH TIME ZONE NOT NULL, 
	duration_minutes INTEGER, 
	max_participants INTEGER, 
	questions_count INTEGER, 
	status olympiadstatus, 
	results_public BOOLEAN, 
	created_by UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
)

;


CREATE TABLE organization_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	address VARCHAR(500), 
	district VARCHAR(100), 
	phone VARCHAR(50), 
	website VARCHAR(200), 
	license_number VARCHAR(50), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
)

;


CREATE TABLE parent_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	occupation VARCHAR(200), 
	subscription_plan VARCHAR(50), 
	subscription_expires_at TIMESTAMP WITH TIME ZONE, 
	max_children_allowed INTEGER, 
	email_notifications BOOLEAN, 
	push_notifications BOOLEAN, 
	weekly_report BOOLEAN, 
	achievement_alerts BOOLEAN, 
	notification_preferences JSON, 
	default_screen_time INTEGER, 
	content_filter_level VARCHAR(20), 
	allowed_time_slots JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
)

;


CREATE TABLE payments (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	amount INTEGER NOT NULL, 
	currency VARCHAR(3), 
	provider paymentprovider NOT NULL, 
	transaction_id VARCHAR(255), 
	status paymentstatus, 
	description VARCHAR(255), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

;


CREATE TABLE quiz_attempts (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	question_id UUID NOT NULL, 
	chosen_option_index INTEGER NOT NULL, 
	is_correct BOOLEAN NOT NULL, 
	coins_earned INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(question_id) REFERENCES quiz_questions (id)
)

;


CREATE TABLE reading_analyses (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	session_date TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	story_title VARCHAR(255), 
	total_words_read INTEGER, 
	reading_time_seconds INTEGER, 
	speech_errors INTEGER, 
	pronunciation_score FLOAT, 
	fluency_score FLOAT, 
	comprehension_score FLOAT, 
	expression_quality FLOAT, 
	total_questions INTEGER, 
	correct_answers INTEGER, 
	answer_quality_score FLOAT, 
	conversation_history JSON, 
	detailed_analysis JSON, 
	ai_feedback TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
)

;


CREATE TABLE crm_leads (
	id SERIAL NOT NULL, 
	first_name VARCHAR NOT NULL, 
	last_name VARCHAR, 
	phone VARCHAR NOT NULL, 
	source VARCHAR, 
	status leadstatus, 
	notes TEXT, 
	assigned_to_id UUID, 
	organization_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(assigned_to_id) REFERENCES users (id), 
	FOREIGN KEY(organization_id) REFERENCES organization_profiles (id)
)

;


CREATE TABLE olympiad_questions (
	id UUID NOT NULL, 
	olympiad_id UUID NOT NULL, 
	question_text TEXT NOT NULL, 
	question_image VARCHAR(500), 
	options JSON NOT NULL, 
	correct_answer INTEGER NOT NULL, 
	points INTEGER, 
	"order" INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(olympiad_id) REFERENCES olympiads (id)
)

;


CREATE TABLE organization_materials (
	id UUID NOT NULL, 
	organization_id UUID NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	file_url VARCHAR(500) NOT NULL, 
	file_type VARCHAR(50), 
	category VARCHAR(100), 
	created_by_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(organization_id) REFERENCES organization_profiles (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_id) REFERENCES users (id)
)

;


CREATE TABLE organization_subscriptions (
	id UUID NOT NULL, 
	organization_id UUID NOT NULL, 
	plan_type VARCHAR(50), 
	start_date TIMESTAMP WITH TIME ZONE, 
	end_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	is_active BOOLEAN, 
	max_teachers INTEGER, 
	max_students INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(organization_id) REFERENCES organization_profiles (id) ON DELETE CASCADE
)

;


CREATE TABLE student_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	parent_user_id UUID, 
	relationship_type childrelationship, 
	organization_id UUID, 
	grade VARCHAR(20), 
	school_name VARCHAR(200), 
	level INTEGER, 
	total_points INTEGER, 
	total_coins INTEGER, 
	current_streak INTEGER, 
	longest_streak INTEGER, 
	total_lessons_completed INTEGER, 
	total_games_played INTEGER, 
	total_time_spent INTEGER, 
	average_score FLOAT, 
	favorite_subjects JSON, 
	avatar_id UUID, 
	preferences JSON, 
	screen_time_limit INTEGER, 
	is_restricted BOOLEAN, 
	last_activity_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(parent_user_id) REFERENCES users (id), 
	FOREIGN KEY(organization_id) REFERENCES organization_profiles (id)
)

;


CREATE TABLE teacher_profiles (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	organization_id UUID, 
	verification_status teacherstatus, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	verified_by UUID, 
	rejection_reason TEXT, 
	specialization VARCHAR(200), 
	qualification VARCHAR(200), 
	years_of_experience INTEGER, 
	bio TEXT, 
	subjects JSON, 
	diploma_url VARCHAR(500), 
	certificate_urls JSON, 
	total_students INTEGER, 
	total_classrooms INTEGER, 
	total_lessons_created INTEGER, 
	rating FLOAT, 
	verification_documents JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(organization_id) REFERENCES organization_profiles (id), 
	FOREIGN KEY(verified_by) REFERENCES users (id)
)

;


CREATE TABLE classrooms (
	id UUID NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT, 
	subject VARCHAR(100), 
	grade_level VARCHAR(20), 
	teacher_id UUID NOT NULL, 
	join_code VARCHAR(8) NOT NULL, 
	is_active BOOLEAN, 
	max_students INTEGER, 
	allow_late_join BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(teacher_id) REFERENCES teacher_profiles (id) ON DELETE CASCADE
)

;


CREATE TABLE crm_activities (
	id SERIAL NOT NULL, 
	lead_id INTEGER NOT NULL, 
	type activitytype, 
	summary VARCHAR NOT NULL, 
	description TEXT, 
	due_date TIMESTAMP WITH TIME ZONE, 
	is_completed BOOLEAN, 
	created_by_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(lead_id) REFERENCES crm_leads (id), 
	FOREIGN KEY(created_by_id) REFERENCES users (id)
)

;


CREATE TABLE game_sessions (
	id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	game_id UUID NOT NULL, 
	profile_id UUID, 
	score INTEGER, 
	points_earned INTEGER, 
	time_spent INTEGER, 
	level INTEGER, 
	is_completed BOOLEAN, 
	game_data JSON, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	ended_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id), 
	FOREIGN KEY(game_id) REFERENCES games (id), 
	FOREIGN KEY(profile_id) REFERENCES users (id)
)

;


CREATE TABLE lessons (
	id UUID NOT NULL, 
	subject_id UUID NOT NULL, 
	teacher_id UUID, 
	title VARCHAR(200) NOT NULL, 
	title_uz VARCHAR(200) NOT NULL, 
	title_ru VARCHAR(200) NOT NULL, 
	description TEXT, 
	description_uz TEXT, 
	description_ru TEXT, 
	content JSON, 
	type lessontype, 
	level INTEGER, 
	age_min INTEGER, 
	age_max INTEGER, 
	duration INTEGER, 
	points_reward INTEGER, 
	thumbnail VARCHAR(500), 
	video_url VARCHAR(500), 
	"order" INTEGER, 
	is_active BOOLEAN, 
	is_ai_generated BOOLEAN, 
	total_completions INTEGER, 
	average_rating FLOAT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(subject_id) REFERENCES subjects (id), 
	FOREIGN KEY(teacher_id) REFERENCES teacher_profiles (id)
)

;


CREATE TABLE live_quizzes (
	id UUID NOT NULL, 
	teacher_id UUID NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	description TEXT, 
	join_code VARCHAR(6) NOT NULL, 
	qr_code_data TEXT, 
	max_participants INTEGER, 
	time_per_question INTEGER, 
	show_leaderboard BOOLEAN, 
	shuffle_questions BOOLEAN, 
	shuffle_options BOOLEAN, 
	status livequizstatus, 
	current_question_index INTEGER, 
	scheduled_start TIMESTAMP WITH TIME ZONE, 
	started_at TIMESTAMP WITH TIME ZONE, 
	ended_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(teacher_id) REFERENCES teacher_profiles (id), 
	UNIQUE (join_code)
)

;


CREATE TABLE olympiad_participants (
	id UUID NOT NULL, 
	olympiad_id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	status participationstatus, 
	registered_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	started_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	total_score INTEGER, 
	correct_answers INTEGER, 
	wrong_answers INTEGER, 
	time_spent_seconds INTEGER, 
	rank INTEGER, 
	coins_earned INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(olympiad_id) REFERENCES olympiads (id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id)
)

;


CREATE TABLE student_achievements (
	id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	achievement_id UUID NOT NULL, 
	profile_id UUID, 
	earned_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id), 
	FOREIGN KEY(achievement_id) REFERENCES achievements (id), 
	FOREIGN KEY(profile_id) REFERENCES users (id)
)

;


CREATE TABLE student_coins (
	id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	total_earned INTEGER, 
	total_spent INTEGER, 
	total_withdrawn INTEGER, 
	current_balance INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (student_id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id)
)

;


CREATE TABLE teacher_subscriptions (
	id UUID NOT NULL, 
	teacher_id UUID NOT NULL, 
	tier subscriptiontier, 
	start_date TIMESTAMP WITH TIME ZONE, 
	end_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	is_active BOOLEAN, 
	auto_renew BOOLEAN, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(teacher_id) REFERENCES teacher_profiles (id) ON DELETE CASCADE
)

;


CREATE TABLE classroom_schedules (
	id UUID NOT NULL, 
	classroom_id UUID NOT NULL, 
	day_of_week VARCHAR(20) NOT NULL, 
	start_time VARCHAR(5) NOT NULL, 
	end_time VARCHAR(5) NOT NULL, 
	subject VARCHAR(100), 
	room_number VARCHAR(50), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(classroom_id) REFERENCES classrooms (id) ON DELETE CASCADE
)

;


CREATE TABLE classroom_students (
	id UUID NOT NULL, 
	classroom_id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	is_active BOOLEAN, 
	joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	left_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_classroom_student UNIQUE (classroom_id, student_id), 
	FOREIGN KEY(classroom_id) REFERENCES classrooms (id) ON DELETE CASCADE, 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id) ON DELETE CASCADE
)

;


CREATE TABLE coin_transactions (
	id UUID NOT NULL, 
	student_coin_id UUID NOT NULL, 
	type transactiontype NOT NULL, 
	amount INTEGER NOT NULL, 
	description VARCHAR(500), 
	reference_id UUID, 
	reference_type VARCHAR(50), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_coin_id) REFERENCES student_coins (id)
)

;


CREATE TABLE coin_withdrawals (
	id UUID NOT NULL, 
	student_coin_id UUID NOT NULL, 
	coin_amount INTEGER NOT NULL, 
	money_amount INTEGER NOT NULL, 
	status withdrawalstatus, 
	parent_id UUID NOT NULL, 
	payment_method VARCHAR(50), 
	payment_details VARCHAR(500), 
	processed_by UUID, 
	processed_at TIMESTAMP WITH TIME ZONE, 
	rejection_reason VARCHAR(500), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_coin_id) REFERENCES student_coins (id), 
	FOREIGN KEY(parent_id) REFERENCES parent_profiles (id), 
	FOREIGN KEY(processed_by) REFERENCES users (id)
)

;


CREATE TABLE live_quiz_participants (
	id UUID NOT NULL, 
	quiz_id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	display_name VARCHAR(50) NOT NULL, 
	avatar_emoji VARCHAR(10), 
	state participantstate, 
	total_score INTEGER, 
	correct_count INTEGER, 
	wrong_count INTEGER, 
	current_streak INTEGER, 
	best_streak INTEGER, 
	rank INTEGER, 
	coins_earned INTEGER, 
	joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	last_activity TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(quiz_id) REFERENCES live_quizzes (id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id)
)

;


CREATE TABLE live_quiz_questions (
	id UUID NOT NULL, 
	quiz_id UUID NOT NULL, 
	question_text TEXT NOT NULL, 
	question_image VARCHAR(500), 
	options JSON NOT NULL, 
	correct_answer INTEGER NOT NULL, 
	points INTEGER, 
	time_limit INTEGER, 
	"order" INTEGER, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(quiz_id) REFERENCES live_quizzes (id)
)

;


CREATE TABLE olympiad_answers (
	id UUID NOT NULL, 
	participant_id UUID NOT NULL, 
	question_id UUID NOT NULL, 
	selected_answer INTEGER, 
	is_correct BOOLEAN, 
	points_earned INTEGER, 
	answered_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	time_spent_seconds INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(participant_id) REFERENCES olympiad_participants (id), 
	FOREIGN KEY(question_id) REFERENCES olympiad_questions (id)
)

;


CREATE TABLE prize_redemptions (
	id UUID NOT NULL, 
	student_coin_id UUID NOT NULL, 
	prize_id UUID NOT NULL, 
	coin_spent INTEGER NOT NULL, 
	quantity INTEGER, 
	delivery_address VARCHAR(500), 
	delivery_status VARCHAR(50), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_coin_id) REFERENCES student_coins (id), 
	FOREIGN KEY(prize_id) REFERENCES prizes (id)
)

;


CREATE TABLE progress (
	id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	lesson_id UUID NOT NULL, 
	profile_id UUID, 
	status progressstatus, 
	score FLOAT, 
	points_earned INTEGER, 
	time_spent INTEGER, 
	attempts INTEGER, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	answers JSON, 
	feedback TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(student_id) REFERENCES student_profiles (id), 
	FOREIGN KEY(lesson_id) REFERENCES lessons (id), 
	FOREIGN KEY(profile_id) REFERENCES users (id)
)

;


CREATE TABLE teacher_lessons (
	id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	teacher_id UUID NOT NULL, 
	classroom_id UUID, 
	join_code VARCHAR(10) NOT NULL, 
	lesson_type teacherlessontype NOT NULL, 
	content JSON, 
	is_active BOOLEAN, 
	is_public BOOLEAN, 
	max_students INTEGER, 
	start_time TIMESTAMP WITH TIME ZONE, 
	end_time TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(teacher_id) REFERENCES users (id), 
	FOREIGN KEY(classroom_id) REFERENCES classrooms (id)
)

;


CREATE TABLE live_quiz_answers (
	id UUID NOT NULL, 
	participant_id UUID NOT NULL, 
	question_id UUID NOT NULL, 
	selected_answer INTEGER, 
	is_correct BOOLEAN, 
	points_earned INTEGER, 
	time_to_answer_ms INTEGER, 
	answered_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(participant_id) REFERENCES live_quiz_participants (id), 
	FOREIGN KEY(question_id) REFERENCES live_quiz_questions (id)
)

;


CREATE TABLE teacher_lesson_students (
	id UUID NOT NULL, 
	lesson_id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	is_active BOOLEAN, 
	joined_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	completion_percentage INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(lesson_id) REFERENCES teacher_lessons (id), 
	FOREIGN KEY(student_id) REFERENCES users (id)
)

;


CREATE TABLE teacher_tests (
	id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	teacher_id UUID NOT NULL, 
	lesson_id UUID, 
	classroom_id UUID, 
	test_type testtype NOT NULL, 
	questions JSON NOT NULL, 
	total_points INTEGER, 
	passing_score INTEGER, 
	time_limit_minutes INTEGER, 
	attempts_allowed INTEGER, 
	is_active BOOLEAN, 
	show_correct_answers BOOLEAN, 
	available_from TIMESTAMP WITH TIME ZONE, 
	available_until TIMESTAMP WITH TIME ZONE, 
	category VARCHAR(100), 
	tags JSON, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(teacher_id) REFERENCES users (id), 
	FOREIGN KEY(lesson_id) REFERENCES teacher_lessons (id), 
	FOREIGN KEY(classroom_id) REFERENCES classrooms (id)
)

;


CREATE TABLE test_results (
	id UUID NOT NULL, 
	test_id UUID NOT NULL, 
	student_id UUID NOT NULL, 
	attempt_number INTEGER, 
	answers JSON NOT NULL, 
	score INTEGER NOT NULL, 
	max_score INTEGER NOT NULL, 
	percentage FLOAT NOT NULL, 
	passed BOOLEAN, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	time_spent_minutes INTEGER, 
	auto_graded BOOLEAN, 
	teacher_comment TEXT, 
	graded_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(test_id) REFERENCES teacher_tests (id), 
	FOREIGN KEY(student_id) REFERENCES users (id)
)

;

